config/routes.rb
PriyankQuestionaire::Application.routes.draw do

  resources :questions do 
    collection do
      get :change_answer_div
      get :ques_tags
      get :make_test
      get :fetch_questions, :as => 'fetch'
      match 'tags/:tag_name', :action => 'tags_index', :as => 'tags_index'
      match 'level/:level_id', :action => 'level_index', :as => 'level_index'
      match 'category/:category_id', :action => 'category_index', :as => 'category_index'
      match 'download/:test_name', :action => 'download', :as => 'download'
      get :show_search
    end
    
    member do
      get :show_fetch_ques
    end
  end
  
  resources :subjectives, :only => [:show, :index], :controller => :questions, :type => "Subjective"
  resources :multiple_choices, :only => [:show, :index], :controller => :questions, :type => "MultipleChoice"
  resources :multiple_choice_answers, :only => [:show, :index], :controller => :questions, :type => "MultipleChoiceAnswer"
  
  devise_for :admins, :controllers => { :omniauth_callbacks => "admins/omniauth_callbacks"}
  
  resources :admins
 
  

  root :to => "questions#index"

end

app/models/question.rb
class Question < ActiveRecord::Base
  
  belongs_to :category, :counter_cache => true

  has_many :options, :dependent => :destroy
  
  has_many :answers, :class_name => "Option", :conditions => { :answer => true }
  
  belongs_to :admin
  
  acts_as_taggable
  acts_as_taggable_on :tags
  
  validates :body, :presence => true
  validates :type, :presence => true
  validates :category_id, :presence => true
  validates :level, :presence => true
  
  #### Priyank -- c['answer'] is been compared to string 'false' that's why the comparison is used as == 'false'
  accepts_nested_attributes_for :options, :allow_destroy => true, :reject_if => lambda {|c| p c; c['body'].blank? && c['answer'] == 'false'}
  
  before_save :valid_provider
  before_save :atleast_two_options, :if => Proc.new { |ques| ques.type != TYPE[1] }
  before_save :atleast_one_answer
  before_save :unique_options_body, :if => Proc.new { |ques| ques.type != TYPE[1] }
  after_update :update_questions_count, :if => Proc.new { |ques| ques.category_id_changed? }
  
  attr_accessible :type, :body, :options_attributes, :tag, :category_id, :level, :provider, :admin_id
  
  attr_accessor :tag
  
  ## Put in options => use validates_uniquess of answer, scope => question
  ## https://github.com/rails/rails/issues/1572
  def unique_options_body
    valid_temp_opts = @options.collect {|opt| opt.body.strip unless opt.body.blank? }.compact
    errors.add('options', 'duplicate options not allowed') and return false if valid_temp_opts.uniq!
  end
  
  ### https://github.com/rails/rails/issues/3891 ###
  def update_questions_count
    Category.reset_counters(category_id_was, :questions)
    Category.reset_counters(category_id, :questions)
  end
  
  def atleast_one_answer
    errors.add('answers', "can't be blank") and return false unless answers?(@options)
  end
  
  
  def atleast_two_options
    opts_temp = @options.select {|opt| !opt.body.blank?}
    if !options?(@options) || !(VALID_OPTIONS_RANGE[:min]..VALID_OPTIONS_RANGE[:max]).include?(opts_temp.length)
      errors.add('options', 'Atleast two options')
      return false 
    end
  end
  
  
  def valid_provider
    if provider.blank?
      self.provider = nil
    end
  end
  
  def self.question_tags(str)
		taggings = tag_counts_on(:tags).collect{|t| [t.id, t.name]}
		question_tags = taggings.select{|tag| tag[1].downcase.match("#{ str }".downcase)}.uniq
    data = Array.new
    question_tags.each do |tag|
     json = Hash.new
     json['name']  = tag[1]
     json['value'] = tag[1]
     data << json
    end
    data
  end  
  
  def self.search_query(tags, type_hash, category, level_hash)
    questions = []
    unless level_hash.values.all? {|val| val.empty? }
      level_hash.each { |level, count| questions += search(tags, type_hash, category, level, count.to_i) unless count.empty?}
    else
      questions = search(tags, type_hash, category)
    end
    
    questions
  end
  
  scope :search, lambda {|tags, type_hash, category, level = false, limit_val = nil|
    conditions = ""
    type = type_hash.values if type_hash
    
    unless tags.empty?
      conditions = "(" + tags.split(/,/).map { |tag| sanitize_sql(["tags.name LIKE ?", tag.to_s]) }.join(" OR ") + ") AND "
      join_query = [:taggings => :tag]
    end
    
    sub_conditions = {:category_id => category.join(',')}
    sub_conditions.merge!({:type => type}) if type
    sub_conditions.merge!({:level => level}) if level
    conditions += sanitize_sql(sub_conditions)
    
    {
      :select => 'DISTINCT questions.*',
      :joins => join_query,
      :conditions => conditions,
      :include => [:options],
      :group => 'RAND()',
      :limit => limit_val
    }
  }
  
  def self.download(name)
    files = Dir.glob(Rails.root.to_s + ZIP_FILE_PATH + "*")
    Zip::Archive.open(Rails.root.to_s + ZIP_FILE_PATH + name + '.zip', Zip::CREATE) do |ar|
      for file in files
        ar.add_file(file)
      end
    end
  end
  
  def self.questions_shuffle(questions)
    questions.shuffle.sort_by{rand}.shuffle
  end
  
  def options_shuffle
    options.shuffle.sort_by{rand}.shuffle
  end
  
  private
  
  def answers?(opts)
    opts.any? {|opt| opt.answer}
  end
  
  def options?(opts)
    opts.empty? ? false : !opts.all? {|opt| opt.body.blank?}
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  

  before_filter :find_question, :only => [:show, :edit, :update, :destroy]
  
  before_filter :admin_signed_in
  
  ## Thinking sphinx on body??
  def index
    if(params[:text].present?)
      #### search on question body using ajax ####
      @questions = Question.where("body like ?", '%'+params[:text]+'%').paginate :include => :category, :page => params[:page], :order => 'updated_at DESC', :per_page => PER_PAGE
    elsif(params[:type])
      @questions = params[:type].constantize.paginate :include => :category, :page => params[:page], :order => 'updated_at DESC', :per_page => PER_PAGE
    else
      @questions = Question.paginate :include => :category, :page => params[:page], :order => 'updated_at DESC', :per_page => PER_PAGE
    end
  end


  def show
    
  end


  def new
    @question = Question.new(:type => 'MultipleChoice')
    @type = @question.type
  end


  def edit
    @type = @question.type
  end


  def create
    @question = Question.new(params[:question])
    @question.tag_list = params[:as_values_tags]
    
    if @question.save
      redirect_to(@question, :notice => 'Question was successfully created.')
    else
      @type = params[:question][:type] 
      render :action => "new"
    end
  end
    
    
  def update
    @question.tag_list = params[:as_values_tags]
    
    if @question.update_attributes(params[:question])
      redirect_to(@question, :notice => 'Question was successfully updated.') 
    else
      @type = params[:question][:type]
      render :action => "edit"
    end
  end


  def destroy
    @question.destroy
    redirect_to(questions_url) 
  end
  

  def tags_index
    @questions = Question.tagged_with(params[:tag_name]).paginate :include => :category, :page => params[:page], :order => 'updated_at DESC', :per_page => PER_PAGE
  end
  
  def level_index
    flash[:notice] = "No Question found for this level!" and redirect_to :root unless LEVEL.any? {|l| l[1] == params[:level_id].to_i }
    @questions = Question.where("level = ?", params[:level_id]).paginate :include => :category, :page => params[:page], :order => 'updated_at DESC', :per_page => PER_PAGE
  end
  
  def category_index
    @category = Category.where(:id => params[:category_id]).first
    unless @category
      flash[:notice] = "No Question found for this category!" 
      return redirect_to :root 
    end  
    @questions = @category.questions.paginate :page => params[:page], :order => 'updated_at DESC', :per_page => PER_PAGE
  end


  def make_test
    
  end
  

  def show_fetch_ques
    @question = Question.where(:id => params[:id]).first
    render :partial => "fetch_ques"
  end
  
  
  def fetch_questions
    @questions = Question.search_query(params[:as_values_tags], params[:type], params[:category_id], params[:level])
  end
  
  
  def change_answer_div
    params[:id].blank? ? @question = Question.new : @question = Question.where(:id => params[:id]).includes(:options).first
  end
  

  def ques_tags
    data = Question.question_tags(params[:q])
		respond_to do |format|			
			format.html{}
			format.js{
				render :json => data
			}			
		end
  end
  

  def download
    name = params[:test_name]
    
    unless FileTest.exists?(Rails.root.to_s + ZIP_FILE_PATH + name +'.zip')
      Question.download(name)
    end
    
    send_file Rails.root.to_s + ZIP_FILE_PATH + name + '.zip', :type => "application/zip"
  end

  private
  
  def find_question
    flash[:notice] = "Question not found." and redirect_to :root unless @question = Question.where(:id => params[:id]).first
  end
  
end

app/helpers/questions_helper.rb
module QuestionsHelper
  
  def tags_in_details
    @question.tag_list.collect { |tag| link_to_if params[:controller] == "questions" && params[:action] == "show", tag, tags_index_questions_path(tag) }.join(", ").html_safe
  end
  
  def correct_answer_tag
    if params[:controller] == "questions" && params[:action] == "show"
      image_tag("correct.jpg", :size => "25x15")
    else
      image_tag("popup_check4.png", :size => "30x15")
    end
  end
  
  def extras question
    content = []
    content << "&lt;<b>Type: </b>#{question.type.titleize}&gt;&nbsp;&nbsp;&nbsp;" unless params[:action] == "index" && params[:type]
    content << "&lt;<b>Level: </b>#{LEVEL[question.level][0]}&gt;&nbsp;&nbsp;&nbsp;" unless params[:action] == "level_index"
    content << "&lt;<b>Category: </b>#{question.category.name}&gt;&nbsp;&nbsp;&nbsp;" unless params[:action] == "category_index"
    content << "&lt;<b>Tags: </b>#{question.tag_list}&gt;" unless question.tag_list.empty?

    content
  end
  
  def ques_number(index, i)
    (index*10)+(i+1)
  end
  
  # Are you writing code in C?
  def count_questions_by_level(questions, level)

    beg = questions.select {|b| b.level == 0}.length
    int = questions.select {|b| b.level == 1}.length
    mast = questions.select {|b| b.level == 2}.length
    
    content = []
    
    content << "<span class='error'><b>Beginner::</b> #{beg}/#{level['0']}&nbsp;&nbsp;</span>" if level["0"].to_i > beg
    content << "<span class='error'><b>Intermediate::</b> #{int}/#{level['1']}&nbsp;&nbsp;</span>" if level["1"].to_i > int
    content << "<span class='error'><b>Master::</b> #{mast}/#{level['2']}&nbsp;&nbsp;</span>" if level["2"].to_i > mast
          
    return content, content.empty?
  end
end

app/views/questions/_details.html.erb
<p class = "title_ques float_left" style = "margin-bottom:10px">
	<b>Question: </b><%= @question.body %>
</p>

<% if @question.provider %>
  <p class = "float_right" style = "margin:20px 10px 0 0">
	<b>Provider: </b><%= @question.provider %></p>
<% end %><br />

<% if @question.type == "Subjective" %>
  <p><b>Answer: </b><%= @question.options.first.body %></p>
<% else %>

  <p style="margin-bottom:2px"><b>Options: </b></p>
  <ol class = "show_options" type = "a">
  
    <% @question.options.each do |option| %>
      <li><%= option.body %>
	
				<% if option.answer %>
          <script>$("li").last().css('font-size','14px')</script>
  				
					<!-- Move in helper -->
          <%= correct_answer_tag %>
  
        <% end %>
      </li>
    <% end %>
  </ol>
  
  <p style="color:red">
		<b>*Note: </b>Ticked options are answers.
	</p>
  
<% end %>

<p class = "extras">
  &lt;<b>Type: </b><%= @question.type.titleize %>&gt;&nbsp;&nbsp;&nbsp;
  &lt;<b>Level: </b><%= LEVEL[@question.level][0] %>&gt;&nbsp;&nbsp;&nbsp;
  &lt;<b>Category: </b><%= @question.category.name %>&gt;&nbsp;&nbsp;&nbsp;
  
  <% if !@question.tag_list.empty? %>
    &lt;<b>Tags: </b>
    <!-- Move in helper -->
		<!-- Use link_to_if -->
    <%= tags_in_details %>
    &gt;
  <% end %>
  
</p><br/>

app/views/questions/_fetch_ques.html.erb
<div class = "show_question" id = "show_ques_partial">
	<%= render "details" %>
</div>

app/views/questions/_fetched_questions.html.erb
<% valid_search = true %>
<% unless params[:level].values.all? {|val| val.empty? } %>
  <% warning, valid_search = count_questions_by_level(@questions, params[:level]) %>
  <%= raw warning.join(" ") %>
<% end %>

<% unless valid_search %>
  <br /><span class = "error"> <b>Warning:</b> Please modify your search</span>
<% end %>

<h2 align ="center"><%= params[:name] %></h2>

<% unless params[:instructions].empty? %>
  <p id = "for_inst"><b>Instructions::</b></p>
  <p id = "for_inst_body">
    <% params[:instructions].split(/\n/).each do |inst| %>
      <%= inst %><br/>
    <% end %>
  </p>
<% end %>

<% unless @questions.empty? %>

  <% questions_per_pages = @questions.in_groups_of(10, false) %>
  <% questions_per_pages.each_with_index do |questions_per_page, index| %>
    <div id = "<%= index+1 %>" class = "pages<%= ' hide' unless index == 0 %>">
    <% questions_per_page.each_with_index do |question, i| %>
    
      <div class = "show_question <%= cycle('list_line_odd', 'list_line_even') %>" style="padding:5px">
        <p class = "title_ques float_left" style = "margin:0">
					<b><%= ques_number(index, i) %>. </b><%= truncate(question.body, :length => 50) %>
				</p>
    
        <div class = "float_right">
          <%= link_to 'Show', show_fetch_ques_question_path(question), :rel => "facebox" %>
        </div><br/>
      </div>
    <% end %>
    </div>
  <% end %>
  
  <% if questions_per_pages.length > 1 %>
  
    <div class = 'pagination'>
      <%= link_to_function '← Previous', "previous_page()", :id => 'previous', :class => 'hide' %>
      <% i = 0 %>
      <% until i == questions_per_pages.length %>
        <%= link_to_function i+1, "paging(#{i+1}, this)", :class => "page_links #{'current' if i+1 == 1}" %>
        <% i += 1 %>
      <% end %>

      <%= link_to_function 'Next →', 'next_page()', :id => 'next' %>
    </div><br />
    
  <% end %>
  
<% else %>
  <p align = "center" class = "error">
		No Question found under this search
	</p>
<% end %>

<% make_doc(params[:name], params[:instructions], @questions, params[:sets]) %>

<% if valid_search %>
  <div align="center">
    <% test_name = params[:name].gsub(/\s+/,"_") %>
    <%= link_to "Download Sets", download_questions_path(test_name) %>
  </div>
<% end %>

<script>
jQuery(document).ready(function($) {
  $('a[rel*=facebox]').facebox()
})
</script>

app/views/questions/_form.html.erb
<% content_for(:js_css) do %>
	<%= stylesheet_link_tag 'ques_form' %>
<% end %>

<%= form_for(@question.becomes(Question)) do |f| %>
  
  <%= render "question", :f => f %>

  <%= f.hidden_field :admin_id, :value => session[:admin_id] %>
  
  <div class="actions">
    
    <% if @question.new_record? %>
      <%= f.submit 'Create Question', :onclick => 'map_tags_and_type()' %>
    <% else %>
      <%= f.submit 'Update Question', :onclick => 'map_tags_and_type()' %>
    <% end %>
    
  </div>

<% end %>

<script>

  $(document).ready(for_ques_ans_tags("<%= @type %>"));
  
  function for_ques_ans_tags(val) {
    if (val == "Subjective") {
      $("#for_option").addClass("hide");
      $("#for_option_error").addClass("hide");
      $('#for_sub').removeClass('hide');
    } else {
      $("#for_option").removeClass("hide");
      $("#for_option_error").removeClass("hide");
      $('#for_sub').addClass('hide');
    }
  }
  
  function change_answer_div(val) {
    if ("<%= !@question.new_record? %>") {
      var id = "<%= params[:id] %>";
    } else {
      var id = null;
    }
    
    for_ques_ans_tags(val);
    
    $.ajax({
      url: '<%= change_answer_div_questions_path %>', 
      dataType: 'script',
      type: 'get', 
      data: 'type='+val+"&id="+id
    });
  }

$("#question_tag").autoSuggest("/questions/ques_tags.js", {minChars: 1, matchCase: false, searchObjProps: "name", startText: "Enter Tags Here", asHtmlID:"tags",  neverSubmit: true, preFill: "<%= @question.tag_list %>"});

</script>

app/views/questions/_multiple_choice.html.erb
<% (OPTIONS_RANGE[:min]..OPTIONS_RANGE[:max]).each do |index| %>
  
  <%= text_field_tag "question[options_attributes][#{index}][body]", @question.try(:options)[index-1].try(:body) %>&nbsp;&nbsp;&nbsp;&nbsp;
  <%= radio_button_tag "answer", value = index, @question.try(:options)[index-1].try(:answer) || index == 1 %><br/>
  
  <% if @question.try(:options)[index-1] %>
  
    <%= hidden_field_tag "question[options_attributes][#{index}][id]", @question.try(:options)[index-1].try(:id) %>
    <%= hidden_field_tag "question[options_attributes][#{index}][_destroy]", false %>
    
  <% end %>
  
  <%= hidden_field_tag "question[options_attributes][#{index}][answer]", false %>
  
<% end %>

app/views/questions/_multiple_choice_answer.html.erb
<% (OPTIONS_RANGE[:min]..OPTIONS_RANGE[:max]).each do |index| %>
  
  <%= text_field_tag "question[options_attributes][#{index}][body]", @question.try(:options)[index-1].try(:body) %>&nbsp;&nbsp;&nbsp;&nbsp;
  <%= check_box_tag "answer_#{index}", value = index, @question.try(:options)[index-1].try(:answer) %><br/>
  
  <% if @question.try(:options)[index-1] %>
  
    <%= hidden_field_tag "question[options_attributes][#{index}][id]", @question.try(:options)[index-1].try(:id) %>
    <%= hidden_field_tag "question[options_attributes][#{index}][_destroy]", false %>

  <% end %>
    
  <%= hidden_field_tag "question[options_attributes][#{index}][answer]", false %>
  
<% end %>

app/views/questions/_question.html.erb
<div id = "form_left">
  
  <div class="field">
    <span class = "label_bold">
		<%= mark_required(@question, :body) %>
		<%= f.label :body, 'Question?' %></span>&nbsp;&nbsp;
		
		<span class='error'> <%= get_error(@question, :body) %></span><br/>
    <%= f.text_area :body, :rows => 5, :cols => 70 %>
  </div>

  <div class="field">
    <span class = "label_bold">
			<%= mark_required(@question, :type) %>
			<%= f.label :type, "Type" %>
		</span><br/>
    
    <% TYPE.each do |type| %>
      <%= f.radio_button :type, type, :checked => @type ? @type == type : type == TYPE[0], :onclick => "change_answer_div(this.value)" %>
      <%= f.label :type, type.titleize %> &nbsp;
    <% end %>
  </div>
  
  <div>
    <span id = "for_option" class = "hide label_bold"> *Options </span>
    <span class = "label_bold">*Answer</span>&nbsp;&nbsp;
		<span class='error'><%= get_error(@question, :answers) %></span>
		<scan class='error' id = "for_sub"><%= get_error(@question, :'options.body') %></span>
  </div>

  <div id = "for_option_error">
		<span class='error'><%= get_error(@question, :options) %></span>
		<scan class='error'><%= get_error(@question, :'options.body') %></span>
	</div>
  
  <div class="field" id = "answer_type">
  	<%= render @type.underscore %>
  </div>
  
  <div class="field">
    <span class = "label_bold"><%= f.label :tag %></span>&nbsp;&nbsp;
    <%= f.text_field :tag, :value => @question.tag_list %><span class='error'><%= get_error(@question, :tag) %></span>
  </div>
  
</div>

<div id = "form_right">

  <div class="field" id = "ques_category">
    <%= mark_required(@question, :category_id) %><%= label_tag "question_category_id", "Category" %>
		<span class='error'> <%= get_error(@question, :category_id) %></span> <br/>
		
    <%= f.select :category_id, Category.all.collect {|c| [c.name, c.id]}, {:prompt => 'Select--'} %>
  </div>

  <div class="field" id = "ques_level">
    <%= mark_required(@question, :level) %>
		<%= f.label :level %><span class='error'> <%= get_error(@question, :level) %></span> <br/>
    <%= f.select :level, LEVEL, {:prompt => 'Select--'} %>
  </div>
  
  <div class = "field" id = "provide">
    <%= f.label :provider, "Provided by:" %><br />
    <%= f.text_field :provider, :size => 25 %>
  </div>
  
</div><br/>

app/views/questions/_subjective.html.erb
<%= text_area_tag "question[options_attributes][1][body]", @question.try(:options).try(:first).try(:body), :rows => 5, :cols => 70 %>
<%= hidden_field_tag "question[options_attributes][1][answer]", true %>

<% unless params[:id].blank? %>
  
  <%= hidden_field_tag 'question[options_attributes][1][id]', @question.options.first.id %>
  
  <% q_length = @question.options.size %>
  <% if q_length >= 2 %>
  
    <% (1...q_length).each do |i| %>
      <%= hidden_field_tag "question[options_attributes][#{i+1}][id]", @question.options[i].id %>
      <%= hidden_field_tag "question[options_attributes][#{i+1}][_destroy]", "1" %>
    <% end %>
    
  <% end %>
  
<% end %>

app/views/questions/edit.html.erb
<h2>Editing question</h2>

<%= render 'form' %>

app/views/questions/index.html.erb
<h2 class = "float_left">
  <%= params[:type]	? "#{params[:type].titleize}" : "Listing questions" %>
</h2>

<p class = "float_right">
	Search: <%= text_field_tag(:search, params[:text], :size => 50) %>
</p>

<br />

<span class = "error"><%= flash[:notice] %></span>

<div id = "showing_ques">
  <%= render "list" %>
</div>

<script>
  $('.pagination a').attr('data-remote', 'true');

  $(document).ready(function() {
    $("#search").keyup(function(e) {
		  // DOnt send ajax if keypressed is enter and esc/tab
      if(e.which == 27 || e.which == 13 || e.which == 9 || e.which == 18) {
        e.preventDefault();
      } else {
        $.ajax({
          url: '<%= questions_path %>', 
          dataType: 'script',
          type: 'get', 
          data: 'text='+$("#search").val()
        });
      }
    });
  });
</script>

app/views/questions/index.js.erb
 $("#showing_ques").html("<%= escape_javascript(render :partial => 'list', :locals => { :questions => @questions }) %>")

app/views/questions/make_test.html.erb
<% content_for(:js_css) do %>
  <%= stylesheet_link_tag 'make_test' %>
  <%= javascript_include_tag 'make_test' %>
<% end %>

<div id = "form_left">

  <h2>Prepare a Test</h2>
	
  <%= form_tag(fetch_questions_path, :remote => true, :method => :get) do %>

    <div class="field">
      <p><b>*<%= label_tag :name %></b>&nbsp;&nbsp;
			<%= text_field_tag :name %>			
			<span class = "error" id = "error1"></span> </p>
    </div>

    <div class="field">
      <p><b>*<%= label_tag :instructions %></b>&nbsp;&nbsp;
				<span class = "error" id = "error4"></span></p>
      <%= text_area_tag :instructions, nil, :rows => 3, :cols => 48 %>
    </div>
        
    <div class="field">
      <p><b><%= label_tag :tag, 'Tags to select Questions' %></b></p>
      <%= text_field_tag :tag %>
    </div>
    
    <div id = "type_cat">

      <div class="field float_left">
				<p><b><%= label_tag :type %></b></p>

				<% TYPE.each do |type| %>
          <p><%= check_box_tag "type[#{type.underscore}]", type %> 
					<%= label_tag 'type_'+type.underscore, type.titleize %></p>
        <% end %>
      </div>
      
      <div class="field float_right" id = "ques_category">
        <p><b><%= label_tag :category_id %></b></p>
      
        <%= select :category_id, nil, options_for_select(Category.all.collect {|c| [c.name, c.id]}), :prompt => "Select a category--" %><br />
      
        <span class = "error" id = "error5"></span>
      </div><br/>
      
    </div>

    <div id = "level_sets">

      <div class="field float_left" id = "ques_level">
        <p><b><%= label_tag :level, 'No. of Questions/Level' %></b>&nbsp;&nbsp;<br /><span class = "error" id = "error3"></span></p>

        <table>

        <% LEVEL.each do |level| %>
          <tr>
            <td><p><%= label_tag "level_#{level[1]}", level[0] %></p></td>
            <td><%= text_field_tag "level[#{level[1]}]",nil , :size => '2' %></td>
          </tr>
        <% end %>

        </table>

      </div>

      <div class="field float_right">
        <p><b>*<%= label_tag :sets, "No. of Sets" %></b>&nbsp;&nbsp;

				 <%= text_field_tag :sets, nil, :size => 1 %></p>

        <span class = "error" id = "error2"></span>
      </div><br/>

    </div>
    
		<div class = "float_right">

			<%= submit_tag 'Generate', :onclick => "return ques_validations()" %>

		</div><br/>

  <% end %>  

</div>

<div id = "form_right">
  <div id = "fetched_ques">
    <h2 align="center">Fetch Questions</h2>
  </div>

</div>

<br/>

<script>
  $("#tag").autoSuggest("/questions/ques_tags.js", {minChars: 1, matchCase: false, searchObjProps: "name", startText: "Enter Tags Here", asHtmlID:"tags",  neverSubmit: true });
</script>

app/views/questions/new.html.erb
<h2 style='margin-bottom:0;'>Add Question</h2>

<%= render 'form' %>

app/views/questions/tags_index.html.erb
<h2>Tag:: <%= params[:tag_name].try(:upcase) %></h2>

<%= render "list" %>