config/routes.rb
PriyankQuestionaire::Application.routes.draw do

  resources :questions do 
    collection do
      get :change_answer_div
      get :ques_tags
      get :make_test
      get :fetch_questions, :as => 'fetch'
      match 'tags/:tag_name', :action => 'tags_index', :as => 'tags_index'
      match 'level/:level_id', :action => 'level_index', :as => 'level_index'
      match 'category/:category_id', :action => 'category_index', :as => 'category_index'
      match 'download/:test_name', :action => 'download', :as => 'download'
      get :show_search
    end
    
    member do
      get :show_fetch_ques
    end
  end
  
  resources :subjectives, :only => [:show, :index], :controller => :questions, :type => "Subjective"
  resources :multiple_choices, :only => [:show, :index], :controller => :questions, :type => "MultipleChoice"
  resources :multiple_choice_answers, :only => [:show, :index], :controller => :questions, :type => "MultipleChoiceAnswer"
  
  devise_for :admins, :controllers => { :omniauth_callbacks => "admins/omniauth_callbacks"}
  
  resources :admins
 
  

  root :to => "questions#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vinsol's Questionnaire</title>
  <%= stylesheet_link_tag 'main', 'autoSuggest','facebox' %>
  <%= yield(:js_css) %>
  <%= javascript_include_tag :defaults, 'jquery.autoSuggest.minified','facebox', 'tab_color', 'nested_form' %>
  <%= csrf_meta_tag %>
</head>

<body>
 <div id="mainHead">
  <h1 style="float:left">Vinsol's Questionnaire</h1>
  <% if session[:admin_id] %>
    <p style="float:right;color:#ffffff;padding-right:35px">Hi!&nbsp;<%= Admin.where("id = ?",session[:admin_id]).first.name.split(" ").select {|n| n[0] = n[0].upcase; n}.join(" ") %></p>
  <% end %><br/>
	<div class="mainMenu" id = "mainMenu">
		<ul class="firstlist" >
		  <% if session["devise.googleapps_data"] %>
			  <li id = "firstlist_1" ><%= link_to "Home", questions_path, :class => class_name("questions", "index") %></li>
			  <li id = "firstlist_2" ><%= link_to "Post Question", new_question_path, :class => class_name("questions", "new") || class_name("questions", "edit") %></li>
			  <li id = "firstlist_3" ><%= link_to "Make Test", make_test_questions_path, :class => class_name("questions", "make_test") %></li>
			<% else %>
			  <li id = "firstlist_5" ><%= link_to "Login", questions_path %></li>
			<% end %>
		</ul>
		<ul class="seclist">
		  <% if session["devise.googleapps_data"] %>
		    <li id = "seclist_1"><%= link_to "Logout", destroy_admin_session_path, :class => class_name("devise/sessions", "destroy") %></li>
			  <li id = "seclist_2"><%= link_to "Add Admin", new_admin_path, :class => class_name("admins", "new") %></li>
			  <li id = "seclist_3"><%= link_to "View Admins", admins_path, :class => class_name("admins", "index") %></li>
			<% end %>
		</ul>
		<br style="clear:both" />
	</div>
	<div class="mainContent">
		<table>
			<tr  valign="top">
				<td >
					  <div id="write" style="">
						  <%= yield %>
				    </div>
					<div class="footer">
						<p>Copyright &#169;2011 Vinayak Solutions</p>
					</div>
				</td>
				<td>
					<div class="rightContent">
					  <% if session["devise.googleapps_data"] %>
						  <div class="leftsub" class = "for_toggle">
						    <h4 style="margin:5px 0;" class = "click">Tags</h4>
						    <div id = "tag_view" >
						      <% Question.tag_counts.each do |tag| %>
						        <div class = "tag_name"><%= link_to tag.name, tags_index_questions_path(tag.name) %></div>
						        <div class = "tag_count"><%= tag.count %></div><br/>
						      <% end %>
						    </div>
						  </div>
						  <div class="leftsub" class = "for_toggle">
							  <h4 style="margin:5px 0;" class = "click">Level</h4>
							    <% LEVEL.each_with_index do |level, index| %>
							      <div class = "level_name"><%= link_to level[0], level_index_questions_path(level[1]) %></div>
							      <div class = "level_count">
							        <%= Question.count(:group => :level)[level[1]] ? Question.count(:group => :level)[level[1]] : 0 %>
						        </div><br/>
							    <% end %>
						  </div>
						  <div class="leftsub" class = "for_toggle">
							  <h4 style="margin:5px 0;" class = "click">Category</h4>
							    
							    <% Category.all.each do |cat| %>
							      <div class = "cat_name"><%= link_to cat.name, category_index_questions_path(cat.id) %></div>
							      <div class = "cat_count">
							        <%= cat.questions.size %>
						        </div><br/>
							    <% end %>
						  </div>
						  <div class="leftsub" class = "for_toggle">
							  <h4 style="margin:5px 0;" class = "click">Type</h4>
							    <% TYPE.each do |type| %>
							      <div class = "type_name"><%= link_to type.titleize, type.underscore.pluralize %></div>
							      <div class = "type_count">
							        <%= type.constantize.count %>
						        </div><br/>
							    <% end %>
						  </div>
						<% else %>
						  <div class="leftsub">
						    <%= image_tag("questionaire.jpg", :height => "230", :width => "100%") %>
							  <h4 style="margin:5px 0;">About</h4>
							  <p style="margin:10px 0;">Now setting a question paper is just a click away. This app stores questions no matter subjective or multiple choice or no matter what is its danger level. Just login and get going.</p>
							  <p class = "error"><b>Note:</b> Login is based on Vinsol's account </p>
						  </div>
						<% end %>
					</div><br style="clear:both" />
				</td>
			</tr>
		</table>
	</div>
</div>
</body>
</html>

<script>
  $(document).ready( function() {
    $($('.click').siblings()).css('display', 'none');
    
    $('.click').click(function() {
      if($($(this).siblings()).css('display') == 'none') {
        $($('.click').siblings()).css('display','none');
        $($(this).siblings()).toggle('slow');
      } else {
        $($(this).siblings()).toggle('slow');
      }
    });
  });
</script>